---
name: ComitandoInvestments
include:
###############################
# Settings
###############################
- path: "./scripts/xcodegen/settings.yml"

###############################
# TargetTemplates
###############################
- path: "./scripts/xcodegen/targetTemplates.yml"

###############################
# Targets
###############################
targets:
  
###############################
# Shcemes
###############################
schemes:
  