---
name: ComitandoInvestments
include:
###############################
# Settings
###############################
- path: "./scripts/xcodegen/settings.yml"

###############################
# TargetTemplates
###############################
- path: "./scripts/xcodegen/targetTemplates.yml"

###############################
# Targets
###############################
targets:
  DependencyInjector:
    templates:
      - DynamicFramework
    templateAttributes:
      frameworkPath: libraries/core/DependencyInjector
  DependencyInjectorTests:
    templates:
      - FrameworkTests
    dependencies:
     - target: DependencyInjector
    templateAttributes:
      frameworkPath: libraries/core/DependencyInjector
  NetworkClient:
    templates:
      - StaticFramework
    dependencies:
     - target: DependencyInjector
     - target: NetworkClientInterface
    templateAttributes:
      frameworkPath: libraries/core/NetworkClient
  NetworkClientTests:
    templates:
      - FrameworkTests
    dependencies:
     - target: NetworkClient
    templateAttributes:
      frameworkPath: libraries/core/NetworkClient
  NetworkClientInterface:
    templates:
      - StaticFramework
    templateAttributes:
      frameworkPath: libraries/core/NetworkClient

###############################
# Shcemes
###############################
schemes:
  DependencyInjector:
      build:
        targets:
          DependencyInjector: [run, test]
      run:
        config: Debug
      test:
        config: Debug
        gatherCoverageData: true
        coverageTargets:
          - DependencyInjector
        targets:
          - name: DependencyInjectorTests
            randomExecutionOrder: true
  NetworkClient:
      build:
        targets:
          NetworkClient: [run, test]
      run:
        config: Debug
      test:
        config: Debug
        gatherCoverageData: true
        coverageTargets:
          - NetworkClient
        targets:
          - name: NetworkClientTests
            randomExecutionOrder: true
  NetworkClientInterface:
      build:
        targets:
          NetworkClientInterface: [run]
      run:
        config: Debug

